apiVersion: v1
kind: Secret
metadata:
  name: otus-zv-secrets-common
  namespace: homework
type: Opaque
stringData:
  tracingCollectorBaseUrl: http://otus-otel-collector.homework.svc.cluster.local:4317
  postgresqlHost: otus-zv-postgres-postgresql.homework.svc.cluster.local
  postgresqlHostMasterPort: "5432"
  postgresqlDbName: zakusvill_auth_db
  postgresqlOptions: Keepalive=30