apiVersion: v1
kind: Secret
metadata:
  name: otus-zv-secrets-auth
  namespace: homework
type: Opaque
stringData:
  authSecretKey: Oksjc9bUCfseaannKvzCqFqN0zA8WAS5
  authPostgresqlUserName: authuser
  authPostgresqlPassword: pass